apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-chart.fullname" . }}
  labels:
    {{- include "notes-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "notes-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
