apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-data-pv
  labels:
    type: local
    environment: production
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s-static-data
    type: DirectoryOrCreate
