apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data-pvc
  labels:
    app: persistent-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
