apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-recreate
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-recreate
  template:
    metadata:
      labels:
        app: app-recreate
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
