apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: ['sh', '-c', 'while true; do echo "$(date) - Service Healthy" >> /var/log/app.log; sleep 1; done']
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
    - name: sidecar-logger
      image: busybox
      command: ['sh', '-c', 'tail -n+1 -f /var/log/app.log']
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
  volumes:
    - name: shared-logs
      emptyDir: {}
