apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: production-webapp
  labels:
    app: web-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: web-app
